name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main, master, dev ]
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches: [ main, master, dev ]

jobs:
  ci:
    name: CI (${{ matrix.os }} - ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: macos-latest
            compiler: clang

    steps:
      - name: Checkout COLA-min-example
        uses: actions/checkout@v6

      - name: Checkout COLA
        uses: actions/checkout@v6
        with:
          repository: ZakayZ/COLA
          ref: tidy
          path: COLA

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev g++ clang-format-19 clang-tidy
          pip install cmake-format

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake googletest coreutils
          echo "$(brew --prefix coreutils)/libexec/gnubin" >> "$GITHUB_PATH"

      - name: Build and install COLA
        working-directory: COLA
        run: |
          cmake --preset release
          cmake --build --preset release --parallel "$(nproc)"
          sudo cmake --install build/release

      - name: Build and test COLA-min-example
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL="$(nproc)"
          cmake --workflow release-test

      - name: Clang-tidy
        id: clang-tidy
        if: matrix.os == 'ubuntu-latest'
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL="$(nproc)"
          cmake --workflow test

      - name: Check formatting
        id: check-format
        if: always() && matrix.os == 'ubuntu-latest'
        run: cmake --workflow check-format
